### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by kylelundstedt** [JakeRuss/cheatsheets#1]
Jake,
I found your blog post via Google, and really enjoyed your Stargazer cheat sheet.  I wanted to offer a few quick comments that I hope you'll find helpful.  

First, the link to this GitHub repo in your blog article is broken.  

Second, as a fellow dplyr enthusiast, I'm curious whether you've looked at the [broom package](https://github.com/dgrtwo/broom).  Basically, broom takes messy output of built-in functions in R, such as lm, nls, or t.test, and turns them into tidy data frames.  It seems more generally applicable than stargazer, but not as handy for specifically outputting tables.

Third, with regard to your cheatsheet's content, I'd love to see more coverage of output options (i.e., LaTeX, Markdown), with examples of how to use stargazer to add tables into various document types.

Anyway, thanks again for all your hard work.  As a subscriber to Reason magazine and a fan of GMU Econ, I wish you the best in your work.

Cheers
Kyle

**Comment by JakeRuss** [comment]
Thank you for your wishes and feedback, Kyle! @kylelundstedt 

I'm actually planning a complete overhaul of my website this weekend, so I will fix that link while I'm cleaning everything else up. I plan to migrate away from my current host to a pure GitHub solution. 

I have seen the `broom` package, though I haven't used it yet. It certainly sounds like it would make using the output of models for further analysis really easy. In that vein I don't see `broom` as a competitor for `stargazer`, but rather complements. `stargazer` is really focused on solely being a tables generator.

I'm still figuring the output to html with the LaTeX options, `knitr` made it easy to knit the markdown into html, so I focused my cheatsheet there. I do plan to continue adding to it as soon as I finish my dissertation. I'm also happy accept pull requests!
