### ISSUE TITLE
Bivariate analysis table using stargazer

### ISSUE THREAD

**Issue by retorquere** [JakeRuss/cheatsheets#10]
I want to construct a bivariate analysis in an Rmarkdown for which I only know the SPSS equivalent procedure (Analyze/Correlate/Bivariate) which produces a table like this (data from World95.sav which comes with SPSS but an Rda copy can be found [here](https://transfer.sh/MXXpx/World95.Rda)):

![spss-bivariate](https://user-images.githubusercontent.com/132108/47369126-49dde800-d6e3-11e8-86ba-4b2ed562a65f.png)

Can I bother you for a addition to the cheat sheet?

**Comment by JakeRuss** [comment]
Sorry, @retorquere, but I haven't touched the stargazer code in three years. I'm not even sure whether such a table is possible or if the stargazer package is still actively maintained. You might try reaching out to Marek.
