### ISSUE TITLE
Posting summary statistics by subgroup?

### ISSUE THREAD

**Issue by jjchern** [JakeRuss/cheatsheets#3]
Thank you for the great cheatsheets!

I was wondering if there is an easy way, perhaps combining with tools such as `dplyr`, to generate descriptive statistics table, such as the following table created by Jörg Weber using Stata command `estout`: 

![table](http://www.jwe.cc/wp-content/uploads/2012/03/table2-229x300.png)

That is, I was looking at a way to post summary statistics by subgroup. Any thought would be appreciated.

**Comment by JakeRuss** [comment]
`stargazer` does not provide this capability. `stargazer` requires that you manipulate your data first and then it will handle the conversion from R data frame object to LaTeX output. 

My advice would be to create a data frame that looks like the table you want, maybe using group summaries with `dplyr` (as you suggested) and then to use stargazer to create the final table output.

Also, as of this writing, `stargazer` does not play nicely with `dplyr`'s `tbl_df` class. Notice in my cheatsheet that after I use `dplyr` I explicitly switch the df back to base R with `data.frame`. I have asked Marek (`stargazer`'s maintainer) to support `tbl_df`.

**Comment by jjchern** [comment]
Again, thank you very much!
