### ISSUE TITLE
robust std errors

### ISSUE THREAD

**Issue by ghost** [JakeRuss/cheatsheets#4]
Concerning the example with robust std errors (replicating stata): The F statistic (and the corresponding sig. level) should be substituted as well, if robust standard errors are used. I guess, one needs to correct that by hand, i. e. `omit.stat = "f"` and `add.lines = list(c("F statistic", "value_mod1", "value_mod2")`, where value_mod1 is the original value and value_mod2 needs to be computed by hand with e. g. `waldtest(output, test="F", vcov=vcov1)`.

If a panelmodel (estimated by plm) is used, the output of `summary( , vcov=)` is wrong due to a bug, see http://stackoverflow.com/questions/31163353/computing-f-statistic-with-user-supplied-covariance-matrix. Thus, we need to substitute here too.

**Comment by ghost** [comment]
ping

**Comment by JakeRuss** [comment]
Sorry it took so long. I have asked Marek to include a replace F option as he did for SE. Will update again if he adds it.
