### ISSUE TITLE
html table formatting

### ISSUE THREAD

**Issue by bjornerstedt** [JakeRuss/cheatsheets#5]
The stargazer cheatsheet is great in summarizing what the program does. Here is a suggestion as a way of saying thanks.

Sometimes it is good to say something about what a program doesn't do. I was having problems with ugly html summary statistics tables, with columns running together. After reading the documentation, and finally the html code I discovered that Stargazer does not format html tables. After a while I managed to solve this with a css file. It is not obvious in the documentation that many formatting directives are for LaTeX, not html.

My small feature request is that you add a sentence or two about html formatting. Something like. 

> Note that the appearance of html tables generated with Stargazer can need improvement. See the markdown documentation about incorporating html style sheets.

/Jonas

**Comment by JakeRuss** [comment]
Thank you for your comments. I will add something like this the next time I update the cheatsheet, which I plan to do soon because I've recently discovered that LaTeX commands and the html work alongside each other within Rmarkdown.  I'm going to add many LaTeX examples.
