### ISSUE TITLE
Omit labels

### ISSUE THREAD

**Issue by JakeRuss** [JakeRuss/cheatsheets#6]
Look at the "Reporting omitted variables" section of the stargazer cheatsheet: both “Quarter dummies?” columns are listed as “No”. The person reporting this issue said Marek has been unresponsive.

**Comment by guanghwang** [comment]
I have this problem too. As a temporary solution, the old version 5.1 works for the omitted label.

**Comment by emraher** [comment]
[This](https://github.com/emraher/cheatsheets/commit/c8737e5498bd55566ccc508cffa2f1a364c6797d?diff=split) may help until its fixed.
