### ISSUE TITLE
buggy output from certain variable names 

### ISSUE THREAD

**Issue by trfetter** [JakeRuss/cheatsheets#8]
I love stargazer, but in a recent application (printing coefficients and other output from an `lm` object) I have found what appears to be a bug regarding the assignment of coefficients to variables, depending on how variables are named. Here's a minimal example (in the actual case there are additional fixed effects in the `lm`, which necessitates the `keep` and `order` statements):

    f1.dot = outcome ~ visible + diffsign + vis.diffsign
    reg1.dot = lm(f1.dot, mydata)
    stargazer(reg1.dot, 
          style = "AER",
          type = "text",
          keep = 
            c("diffsign", "visible", "vis.diffsign"),
          order = 
            c("diffsign", "visible", "vis.diffsign"),
          covariate.labels = 
            c("Diff Sign", "Visible", "Visible * Diff Sign"),
          dep.var.labels = c("Outcome"),
          keep.stat = c("n", "rsq"),
          align = TRUE)
    summary(reg1.dot)

The stargazer output mixes up the coefficients on `visible` and `vis.diffsign`, based on comparing stargazer output with the output of a simple `summary()`. The same is true if I rename that interaction term `vis_diffsign` or even `visdiffsign` (no special characters, but shares the first three characters with another variable in the same object). However, if I rename it `fred`, the stargazer output is correct.

I assume there is a regex function in the code that's looking into the `lm` object for arguments passed to the `keep` and/or `order` statements, but that function breaks under certain conditions. I could not find any indication of those conditions in the stargazer documentation. A simple solution would be to clarify what restrictions users should apply to variable names to avoid buggy output. A more complex (and complete) solution would be, of course, to change that regex to allow a broader set of variable names.

Thanks!

**Comment by JakeRuss** [comment]
Thanks for the bug report, @trfetter, but I am not the maintainer of this package. All this repo is for is a cheatsheet I wrote in grad school. I haven't kept up with it, but you should try contacting Marek Hlavac.  [https://sites.google.com/site/marekhlavac/marekhlavac?authuser=0](url)
